framework:
    asset_mapper:
        vendor_dir: '%kernel.project_dir%/assets/vendors'
        # The paths to make available to the asset mapper.
        paths:
            - assets/
        missing_import_mode: strict

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
            
when@test:
    framework:
        asset_mapper:
            vendor_dir: '%kernel.project_dir%/assets/vendors'
            missing_import_mode: warn
